---
title: "Week1_HW_605"
author: "(Xiaomeng)Vivian Kong"
date: "1/30/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

---
# Problem 1

```{r}
u <- c(0.5, 0.5)
v <- c(3, -4)

# 1) Calculate the product of u.v

dot <- u %*% v

dot

# 2) What are the length of u and v?

um <- sqrt (sum(u^2))
um

vm <- sqrt (sum(v^2))
vm

# 3) What is the linear combination : 3u -2v?

lm <- 3*u -2*v
lm

# 4) What is the angle between u and v?

angle_rad <- acos(dot/(um * vm))
angle_rad
angle_rad * 180 / pi
```


---
# Problem 2

```{r}
linearsystem <- function (A, b) {
  # let x store the outputs
  x = numeric (3)
  m = cbind(A,b)
  
  # find 1 in the top left piviot
  
  if(m[1,1]==0){
    if(m[2,2]!=0){
      m= m[c(2,1,3),]   # switch row 1 and row 2 when the top left piviot is 0.
    }
    else
    {m=m[3,1,2]}    # Otherwise switch row 1 and row 3. 
  }
 else if (m[1,1]!=1) {
  m[1,] <-m[1,]/m[1,1]    # Get 1 by dividing the top left piviot itself 
}

  # check the second row and first column 
if (m[2,1]!=0){       
  vect <- m[2,1]*m[1,]  # multiply the first row with the entry of 2nd row and 1st column to get the new vector
  m[2,]<- -m[2,]+vect   # Use the new vector to make the entry of the 2nd row and 1st column to get 0 for that position
}
if (m[3,1]!=0){         # same procedure as the last step for the 3rd row
  vect <- m[3,1]*m[1,]
  m[3,] <- -m[3,]+vect
}

if (m[2,2]==0){           # If the new piviot column for 2nd row is 0, switch the 3rd and 2nd row
  m=m[c(1,3,2),]
}
m[2,] <- m[2, ]/m[2,2]
vect <- m[3,2]*m[2,]
m[3,] <- -m[3,]+vect

x[3]<- m[3,4]/m[3,3]              # to get x3, divide the piviot position from the 3rd row to get the answer 
x[2]<- (m[2,4]-m[2,3]*x[3])/ m[2,2]  # substitute x3 for the reduced second row and solve for x2
x[1] <- (m[1,4]-m[1,2]*x[2]-m[1,3]*x[3]) / m[1,1]  # substitute x2 and x3 for the reduced first row and solve for x1

return(x)
}


# Try
A <- matrix(c(1,1,3,2,-1,5,-1,-2,4), 3, byrow=T)
b <- matrix(c(1,2,6))

linearsystem(A,b)


# My own Example

A <- matrix (c(1,-2,1,0,2,-8,5,0,-5), 3, byrow=T)
b <- matrix(c(0,8,10))

linearsystem(A,b)

# For this matrix, I expect that x2 and x3 are free variables.
A <- matrix (c(0,1,4,1,3,5,3,7,7), 3, byrow=T)
b <- matrix (c(5,-2,6))
linearsystem(A,b)
```

